version: '3.3'

services:
  db:
    image : postgres:${TAG}
    restart: always
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env

  web:
    image: nginx:1.19.3
    volumes:
      - ./images:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"
    restart: always
